services:
  mysql:
    image: mysql:latest
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - url-shortener
  tinyurl:
    image: songkg7/url-shortener
    container_name: tinyurl
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge
